create hybrid_jobs and qiskit
aws-samples/amazon-braket-examples-jp pull request #12
Opened 2023-05-24 14:53 UTC by YutoTakaki

*Issue #, if available:*

*Description of changes:*
create hybrid_jobs and qiskit.

original:
**hybrid_jobs**

- https://github.com/aws/amazon-braket-examples/tree/main/examples/hybrid_jobs/0_Creating_your_first_Hybrid_Job
- https://github.com/aws/amazon-braket-examples/tree/main/examples/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs
- https://github.com/aws/amazon-braket-examples/tree/main/examples/hybrid_jobs/4_Embedded_simulators_in_Braket_Jobs

**qiskit**

- https://github.com/qiskit-community/qiskit-braket-provider/blob/main/docs/tutorials/0_tutorial_qiskit-braket-provider_overview.ipynb

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-26 16:38 UTC, hariby commented on workshop/2_QPU_devices.ipynb
TODO
- OQC にも `device.properties.dict()['paradigm']['connectivity']` を足す。
- この[ノートブック](https://github.com/aws/amazon-braket-examples/blob/main/examples/braket_features/Verbatim_Compilation.ipynb) にあるように、NetworkX で可視化した方が分かりやすそう (そうしないと結局マネコンを見に行かないとトポロジーが分かりづらい)。

2023-05-26 16:45 UTC, hariby commented on workshop/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job.ipynb
> +    "Amazon Braket Hybrid Jobsを初めて使用する場合、[適切な権限](https://docs.aws.amazon.com/braket/latest/developerguide/braket-manage-access.html#about-amazonbraketjobsexecution)を持つ IAM ロールを作成する必要があります。このロールはジョブがア
ドキュメントも日本語リンクで良さそう。
https://docs.aws.amazon.com/ja_jp/braket/latest/developerguide/braket-manage-access.html#about-amazonbraketjobsexecution

2023-05-26 16:51 UTC, hariby commented on workshop/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job.ipynb
> +    "# print(job.logs())  # ログを出力したい場合はコメントアウトしてください"
既にコメントアウトされているので、「コメントアウトを外してください」など。

2023-05-26 16:54 UTC, hariby commented on workshop/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job.ipynb
> +    "ローカルでジョブを実行するには、Docker デーモンが起動していることを確認し、`AwsQuantumJob` の代わりに `LocalQuantumJob` を作成するだけです。ローカルジョブは常に同期して実行され、ログが表示されます。"
synchronously: 同期的に
が自然かと思います。

2023-05-26 16:56 UTC, hariby commented on workshop/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job.ipynb
> +    "`AwsQuantumJob.create` を使用してプログラムで Braket Job を作成する以外に、Braket コンソールでジョブを作成するオプションがあります。[こちらのリンク](https://us-west-2.console.aws.amazon.com/braket/home#/job/create) を参照して、\\\"Create job\\\" ページをご確
「ユニークな」->「一意の」の方が日本語では自然。

2023-05-26 16:59 UTC, hariby commented on workshop/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job.ipynb
> +    "`AwsQuantumJob.create` を使用してプログラムで Braket Job を作成する以外に、Braket コンソールでジョブを作成するオプションがあります。[こちらのリンク](https://us-west-2.console.aws.amazon.com/braket/home#/job/create) を参照して、\\\"Create job\\\" ページをご確
> Amazon Braket は、S3 バケットとフォルダが存在しない場合、お客様に変わって作成します。

より以下の方が少し自然。

> S3 バケットとフォルダが存在しない場合、Amazon Braket がお客様の代わりに作成します。

2023-05-26 17:12 UTC, hariby commented on workshop/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs.ipynb
> +    "QAOA と PennyLane についてさらに知りたい方は、[こちらの example notebook](../../pennylane/2_Graph_optimization_with_QAOA/2_Graph_optimization_with_QAOA.ipynb) や [こちらの PennyLane チュートリアル](https://pennylane.ai/qml/de
> [こちらの example notebook](../../pennylane/2_Graph_optimization_with_QAOA/2_Graph_optimization_with_QAOA.ipynb)

この相対リンクがうまく開けなかったです。

2023-05-26 17:26 UTC, hariby commented on workshop/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs.ipynb
> +    "Max-Cut 問題は、与えられたグラフを 2 つに分割した時に、分割する辺の数を最大にするような切り方を探す問題です。理論物理や組み合わせ最適化の分野で応用されています。はじめに、<code>networkx</code> パッケージを用いて Max-Cut 問題用のランダムなグラフを作成し、可視化します。オプションとして、ノード数 <code>n</code> や辺の数 <code
> Max-Cut 問題は、与えられたグラフを 2 つに分割した時に、分割する辺の数を最大にするような切り方を探す問題です。

個人的には以下の方が自然かな (「カット」は専門用語)

> Max-Cut 問題は、与えられたグラフを 2 つに分割する時に、その2つにまたがる辺の数を最大にするようなカットを探す問題です。

2023-05-26 17:27 UTC, hariby commented on workshop/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs.ipynb
> +    "Max-Cut 問題は、与えられたグラフを 2 つに分割した時に、分割する辺の数を最大にするような切り方を探す問題です。理論物理や組み合わせ最適化の分野で応用されています。はじめに、<code>networkx</code> パッケージを用いて Max-Cut 問題用のランダムなグラフを作成し、可視化します。オプションとして、ノード数 <code>n</code> や辺の数 <code
「組み合わせ最適化」->「組合せ最適化」

2023-05-26 17:40 UTC, hariby commented on workshop/hybrid_jobs/4_Embedded_simulators_in_Braket_Jobs/Embedded_simulators_in_Braket_Jobs.ipynb
> +    "# Braket Jobs の組み込みシミュレータ"
ドキュメント上の表記に合わせて頂いているかと思いますが、個人的に「組み込みシミュレータ」ってあまり良い訳語ではないと感じていて、まだ「埋め込みシミュレータ」の方がイメージに近いかなと思います。ただ、独自用語を生み出すのも微妙なので、訳さず "Embedded Simulator" で通すのはいかがでしょう？？

2023-05-26 17:52 UTC, hariby commented on workshop/hybrid_jobs/4_Embedded_simulators_in_Braket_Jobs/Embedded_simulators_in_Braket_Jobs.ipynb
> +    "量子回路の変分パラメータに対するコスト関数の勾配を計算する一般的な方法として、パラメータシフト法があります。パラメータシフト法では、パラメータをシフトした回路を複数回実行することで、勾配を正確に計算することができます。しかし，SV1 のような並列性の高いシミュレータを用いない限り，シフトされた回路をすべて実行するのは非常に時間がかかります。またその場合でも、回路数はパラメータ数に対して
パラメータシフト法のリンクが貼られていない

2023-05-26 17:57 UTC, hariby requested changes
和訳ありがとうございます、いくつか細かいコメントを付けました！

2023-05-28 04:24 UTC, YutoTakaki commented on workshop/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job.ipynb
> +    "In this example, the algorithm is defined by a single file, so the `source_module` is `algorithm_script.py`. Depending on your application, there are other options for setting the source module.
Done. 原文削除しました。

2023-05-28 04:24 UTC, YutoTakaki commented on workshop/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job.ipynb
> +    "# print(job.logs())  # ログを出力したい場合はコメントアウトしてください"
Done.  「コメントアウトしてください」->「コメントアウトを外してください」

2023-05-28 04:24 UTC, YutoTakaki commented on workshop/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job.ipynb
> +    "ローカルでジョブを実行するには、Docker デーモンが起動していることを確認し、`AwsQuantumJob` の代わりに `LocalQuantumJob` を作成するだけです。ローカルジョブは常に同期して実行され、ログが表示されます。"
Done. 「同期して」->「同期的に」

2023-05-28 04:24 UTC, YutoTakaki commented on workshop/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job.ipynb
> +    "`AwsQuantumJob.create` を使用してプログラムで Braket Job を作成する以外に、Braket コンソールでジョブを作成するオプションがあります。[こちらのリンク](https://us-west-2.console.aws.amazon.com/braket/home#/job/create) を参照して、\\\"Create job\\\" ページをご確
Done. 「ユニークな」->「一意の」

2023-05-28 04:24 UTC, YutoTakaki commented on workshop/hybrid_jobs/0_Creating_your_first_Hybrid_Job/Creating_your_first_Hybrid_Job.ipynb
> +    "`AwsQuantumJob.create` を使用してプログラムで Braket Job を作成する以外に、Braket コンソールでジョブを作成するオプションがあります。[こちらのリンク](https://us-west-2.console.aws.amazon.com/braket/home#/job/create) を参照して、\\\"Create job\\\" ページをご確
Done. 

> Amazon Braket は、S3 バケットとフォルダが存在しない場合、お客様に変わって作成します。

↓

> S3 バケットとフォルダが存在しない場合、Amazon Braket がお客様の代わりに作成します。

2023-05-28 04:25 UTC, YutoTakaki commented on workshop/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs.ipynb
> +    "QAOA と PennyLane についてさらに知りたい方は、[こちらの example notebook](../../pennylane/2_Graph_optimization_with_QAOA/2_Graph_optimization_with_QAOA.ipynb) や [こちらの PennyLane チュートリアル](https://pennylane.ai/qml/de
Done.
相対リンクを
https://github.com/aws/amazon-braket-examples/blob/main/examples/pennylane/2_Graph_optimization_with_QAOA/2_Graph_optimization_with_QAOA.ipynb
に変更しました。

2023-05-28 04:25 UTC, YutoTakaki commented on workshop/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs.ipynb
> +    "Max-Cut 問題は、与えられたグラフを 2 つに分割した時に、分割する辺の数を最大にするような切り方を探す問題です。理論物理や組み合わせ最適化の分野で応用されています。はじめに、<code>networkx</code> パッケージを用いて Max-Cut 問題用のランダムなグラフを作成し、可視化します。オプションとして、ノード数 <code>n</code> や辺の数 <code
Done.

> Max-Cut 問題は、与えられたグラフを 2 つに分割した時に、分割する辺の数を最大にするような切り方を探す問題です。

↓

> Max-Cut 問題は、与えられたグラフを 2 つに分割する時に、その2つにまたがる辺の数を最大にするようなカットを探す問題です。

2023-05-28 04:25 UTC, YutoTakaki commented on workshop/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs.ipynb
> +    "Max-Cut 問題は、与えられたグラフを 2 つに分割した時に、分割する辺の数を最大にするような切り方を探す問題です。理論物理や組み合わせ最適化の分野で応用されています。はじめに、<code>networkx</code> パッケージを用いて Max-Cut 問題用のランダムなグラフを作成し、可視化します。オプションとして、ノード数 <code>n</code> や辺の数 <code
Done. 「組み合わせ最適化」->「組合せ最適化」

2023-05-28 04:25 UTC, YutoTakaki commented on workshop/hybrid_jobs/2_Using_PennyLane_with_Braket_Jobs/Using_PennyLane_with_Braket_Jobs.ipynb
> +    "次に、いわゆるイジング行列として表される、解きたい最適化問題を Braket Job の入力データとして用意します。このベストプラクティスにより、問題の定義とアルゴリズムコードを切り離して考えることができます。形式は同じで、サイズの違う問題を考えたくなった際は、新しい入力データを用意するだけですみます。入力データはローカルファイルのパスか、S3 のパスとして指定します。今回の例では、ロ
Done. 「イジング行列」->「隣接リスト」

2023-05-28 04:25 UTC, YutoTakaki commented on workshop/hybrid_jobs/4_Embedded_simulators_in_Braket_Jobs/Embedded_simulators_in_Braket_Jobs.ipynb
> +    "量子回路の変分パラメータに対するコスト関数の勾配を計算する一般的な方法として、パラメータシフト法があります。パラメータシフト法では、パラメータをシフトした回路を複数回実行することで、勾配を正確に計算することができます。しかし，SV1 のような並列性の高いシミュレータを用いない限り，シフトされた回路をすべて実行するのは非常に時間がかかります。またその場合でも、回路数はパラメータ数に対して
Done. リンクを貼りました。

2023-05-28 06:53 UTC, YutoTakaki commented
レビューありがとうございます。いただいたレビュー内容を反映しました！

2023-05-28 09:36 UTC, hariby approved these changes
修正ありがとうございました！

2023-05-28 09:36 UTC, merged